"""added mfa

Revision ID: 86ae8706e218
Revises: c2e21426a9ca
Create Date: 2026-09-28 18:28:04.384157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ae8706e218'
down_revision: Union[str, Sequence[str], None] = 'c2e21426a9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: add as nullable with a server-side default so existing rows are filled
    op.add_column(
        'users',
        sa.Column('mfa_enabled', sa.Boolean(), nullable=True, server_default=sa.false()),
    )
    op.add_column(
        'users',
        sa.Column('mfa_secret_encrypted', sa.String(length=500), nullable=True),
    )

    # Step 2: backfill any NULLs (server_default already handles this, but be explicit)
    op.execute("UPDATE users SET mfa_enabled = FALSE WHERE mfa_enabled IS NULL")

    # Step 3: tighten to NOT NULL
    op.alter_column('users', 'mfa_enabled', nullable=False)

    # Step 4: drop the server_default now that we're done (matches model definition)
    op.alter_column('users', 'mfa_enabled', server_default=None)
    
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_secret_encrypted')
    op.drop_column('users', 'mfa_enabled')
    # ### end Alembic commands ###
