"""added more video of youtube like 

Revision ID: b8c03d32c534
Revises: 
Create Date: 2026-09-17 19:04:44.729400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8c03d32c534'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_key', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('usage_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('profile_pic', sa.String(length=500), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('channel_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('banner_key', sa.String(length=500), nullable=True),
    sa.Column('avatar_key', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('subscriber_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('video_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_view_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_uuid'),
    sa.UniqueConstraint('handle'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_index('ix_channels_deleted_at', 'channels', ['deleted_at'], unique=False)
    op.create_index('ix_channels_owner_id', 'channels', ['owner_id'], unique=False)
    op.create_table('playlists',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('playlist_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=20), server_default='private', nullable=False),
    sa.Column('thumbnail_key', sa.String(length=500), nullable=True),
    sa.Column('video_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("visibility IN ('private','unlisted','public')", name='ck_playlists_visibility'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_uuid')
    )
    op.create_index('ix_playlists_owner_id_created_at', 'playlists', ['owner_id', 'created_at'], unique=False)
    op.create_table('channel_grants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('grantee_type', sa.String(length=20), nullable=False),
    sa.Column('grantee_user_id', sa.Integer(), nullable=True),
    sa.Column('link_token', sa.String(length=64), nullable=True),
    sa.Column('granted_by_id', sa.Integer(), nullable=True),
    sa.Column('can_view', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('can_download', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_reshare', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(grantee_type='user' AND grantee_user_id IS NOT NULL AND link_token IS NULL) OR (grantee_type='link' AND link_token IS NOT NULL AND grantee_user_id IS NULL)", name='ck_channel_grants_grantee_xor'),
    sa.CheckConstraint("grantee_type IN ('user','link')", name='ck_channel_grants_grantee_type'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grantee_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'grantee_user_id', name='uq_channel_grants_channel_grantee'),
    sa.UniqueConstraint('link_token')
    )
    op.create_index('ix_channel_grants_channel_id_revoked_at', 'channel_grants', ['channel_id', 'revoked_at'], unique=False)
    op.create_index('ix_channel_grants_grantee_user_id_created_at', 'channel_grants', ['grantee_user_id', 'created_at'], unique=False)
    op.create_table('channel_members',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='viewer', nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('editor','viewer')", name='ck_channel_members_role'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', 'user_id')
    )
    op.create_index('ix_channel_members_user_id', 'channel_members', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('notify', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscriber_id', 'channel_id')
    )
    op.create_index('ix_subscriptions_channel_id_created_at', 'subscriptions', ['channel_id', 'created_at'], unique=False)
    op.create_index('ix_subscriptions_subscriber_id_created_at', 'subscriptions', ['subscriber_id', 'created_at'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('video_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('thumbnail_key', sa.String(length=500), nullable=True),
    sa.Column('storage_bucket', sa.String(length=100), nullable=False),
    sa.Column('storage_prefix', sa.String(length=500), nullable=False),
    sa.Column('master_playlist_key', sa.String(length=500), server_default='master.m3u8', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='processing', nullable=False),
    sa.Column('visibility', sa.String(length=20), server_default='private', nullable=False),
    sa.Column('view_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('like_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('dislike_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('save_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('share_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_size_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('processing','ready','failed','deleted')", name='ck_videos_status'),
    sa.CheckConstraint("visibility IN ('private','unlisted','public')", name='ck_videos_visibility'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_uuid')
    )
    op.create_index('ix_videos_channel_id_created_at', 'videos', ['channel_id', 'created_at'], unique=False)
    op.create_index('ix_videos_channel_id_published_at', 'videos', ['channel_id', 'published_at'], unique=False)
    op.create_index('ix_videos_deleted_at', 'videos', ['deleted_at'], unique=False)
    op.create_index('ix_videos_status', 'videos', ['status'], unique=False)
    op.create_index('ix_videos_visibility_published_at', 'videos', ['visibility', 'published_at'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('comment_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('depth', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('like_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('reply_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('depth BETWEEN 0 AND 3', name='ck_comments_depth'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_uuid')
    )
    op.create_index('ix_comments_deleted_at', 'comments', ['deleted_at'], unique=False)
    op.create_index('ix_comments_parent_comment_id', 'comments', ['parent_comment_id'], unique=False)
    op.create_index('ix_comments_user_id_created_at', 'comments', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_comments_video_id_created_at', 'comments', ['video_id', 'created_at'], unique=False)
    op.create_table('playlist_videos',
    sa.Column('playlist_id', sa.BigInteger(), nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'video_id'),
    sa.UniqueConstraint('playlist_id', 'position', name='uq_playlist_videos_position')
    )
    op.create_index('ix_playlist_videos_video_id', 'playlist_videos', ['video_id'], unique=False)
    op.create_table('saved_videos',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'video_id')
    )
    op.create_index('ix_saved_videos_user_id_saved_at', 'saved_videos', ['user_id', 'saved_at'], unique=False)
    op.create_table('video_categories',
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'category_id')
    )
    op.create_index('ix_video_categories_category_id', 'video_categories', ['category_id'], unique=False)
    op.create_table('video_grants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('grantee_type', sa.String(length=20), nullable=False),
    sa.Column('grantee_user_id', sa.Integer(), nullable=True),
    sa.Column('link_token', sa.String(length=64), nullable=True),
    sa.Column('granted_by_id', sa.Integer(), nullable=True),
    sa.Column('can_view', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('can_download', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_reshare', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(grantee_type='user' AND grantee_user_id IS NOT NULL AND link_token IS NULL) OR (grantee_type='link' AND link_token IS NOT NULL AND grantee_user_id IS NULL)", name='ck_video_grants_grantee_xor'),
    sa.CheckConstraint("grantee_type IN ('user','link')", name='ck_video_grants_grantee_type'),
    sa.CheckConstraint('grantee_user_id IS NULL OR granted_by_id IS NULL OR granted_by_id <> grantee_user_id', name='ck_video_grants_no_self_grant'),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grantee_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_token'),
    sa.UniqueConstraint('video_id', 'grantee_user_id', name='uq_video_grants_video_grantee')
    )
    op.create_index('ix_video_grants_grantee_user_id_created_at', 'video_grants', ['grantee_user_id', 'created_at'], unique=False)
    op.create_index('ix_video_grants_video_id_revoked_at', 'video_grants', ['video_id', 'revoked_at'], unique=False)
    op.create_table('video_impressions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('watched_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('counted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(user_id IS NOT NULL AND session_id IS NULL) OR (user_id IS NULL AND session_id IS NOT NULL)', name='ck_video_impressions_user_or_session'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_impressions_counted', 'video_impressions', ['counted'], unique=False)
    op.create_index('ix_video_impressions_user_id_created_at', 'video_impressions', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_video_impressions_video_id_created_at', 'video_impressions', ['video_id', 'created_at'], unique=False)
    op.create_table('video_reactions',
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reaction IN ('like','dislike')", name='ck_video_reactions_reaction'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'user_id')
    )
    op.create_index('ix_video_reactions_user_id_created_at', 'video_reactions', ['user_id', 'created_at'], unique=False)
    op.create_table('video_tags',
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'tag_id')
    )
    op.create_index('ix_video_tags_tag_id', 'video_tags', ['tag_id'], unique=False)
    op.create_table('video_variants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.Column('codec', sa.String(length=20), server_default='h264', nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('playlist_key', sa.String(length=500), nullable=False),
    sa.Column('segment_count', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("codec IN ('h264','h265','av1','vp9')", name='ck_video_variants_codec'),
    sa.CheckConstraint("quality IN ('240p','360p','480p','720p','1080p','1440p','2160p')", name='ck_video_variants_quality'),
    sa.CheckConstraint("status IN ('pending','processing','ready','failed')", name='ck_video_variants_status'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'quality', 'codec', name='uq_video_variants_video_quality_codec')
    )
    op.create_table('watch_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('last_position_sec', sa.Integer(), server_default='0', nullable=False),
    sa.Column('watched_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_watch_history_user_video')
    )
    op.create_index('ix_watch_history_channel_id', 'watch_history', ['channel_id'], unique=False)
    op.create_index('ix_watch_history_user_id_last_watched_at', 'watch_history', ['user_id', 'last_watched_at'], unique=False)
    op.create_table('comment_likes',
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('new_video','comment','reply','like','subscribe','mention','system')", name='ck_notifications_type'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_recipient_id_created_at', 'notifications', ['recipient_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_recipient_id_is_read_created_at', 'notifications', ['recipient_id', 'is_read', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_recipient_id_is_read_created_at', table_name='notifications')
    op.drop_index('ix_notifications_recipient_id_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('comment_likes')
    op.drop_index('ix_watch_history_user_id_last_watched_at', table_name='watch_history')
    op.drop_index('ix_watch_history_channel_id', table_name='watch_history')
    op.drop_table('watch_history')
    op.drop_table('video_variants')
    op.drop_index('ix_video_tags_tag_id', table_name='video_tags')
    op.drop_table('video_tags')
    op.drop_index('ix_video_reactions_user_id_created_at', table_name='video_reactions')
    op.drop_table('video_reactions')
    op.drop_index('ix_video_impressions_video_id_created_at', table_name='video_impressions')
    op.drop_index('ix_video_impressions_user_id_created_at', table_name='video_impressions')
    op.drop_index('ix_video_impressions_counted', table_name='video_impressions')
    op.drop_table('video_impressions')
    op.drop_index('ix_video_grants_video_id_revoked_at', table_name='video_grants')
    op.drop_index('ix_video_grants_grantee_user_id_created_at', table_name='video_grants')
    op.drop_table('video_grants')
    op.drop_index('ix_video_categories_category_id', table_name='video_categories')
    op.drop_table('video_categories')
    op.drop_index('ix_saved_videos_user_id_saved_at', table_name='saved_videos')
    op.drop_table('saved_videos')
    op.drop_index('ix_playlist_videos_video_id', table_name='playlist_videos')
    op.drop_table('playlist_videos')
    op.drop_index('ix_comments_video_id_created_at', table_name='comments')
    op.drop_index('ix_comments_user_id_created_at', table_name='comments')
    op.drop_index('ix_comments_parent_comment_id', table_name='comments')
    op.drop_index('ix_comments_deleted_at', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_videos_visibility_published_at', table_name='videos')
    op.drop_index('ix_videos_status', table_name='videos')
    op.drop_index('ix_videos_deleted_at', table_name='videos')
    op.drop_index('ix_videos_channel_id_published_at', table_name='videos')
    op.drop_index('ix_videos_channel_id_created_at', table_name='videos')
    op.drop_table('videos')
    op.drop_index('ix_subscriptions_subscriber_id_created_at', table_name='subscriptions')
    op.drop_index('ix_subscriptions_channel_id_created_at', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_channel_members_user_id', table_name='channel_members')
    op.drop_table('channel_members')
    op.drop_index('ix_channel_grants_grantee_user_id_created_at', table_name='channel_grants')
    op.drop_index('ix_channel_grants_channel_id_revoked_at', table_name='channel_grants')
    op.drop_table('channel_grants')
    op.drop_index('ix_playlists_owner_id_created_at', table_name='playlists')
    op.drop_table('playlists')
    op.drop_index('ix_channels_owner_id', table_name='channels')
    op.drop_index('ix_channels_deleted_at', table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_index('ix_categories_parent_id', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
