"""added few more column in video

Revision ID: f0f0913c346a
Revises: b8c03d32c534
Create Date: 2026-09-22 17:28:15.634325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f0913c346a'
down_revision: Union[str, Sequence[str], None] = 'b8c03d32c534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('videos', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.create_index('ix_videos_processing_started_at', 'videos', ['processing_started_at'], unique=False, postgresql_where=sa.text("status = 'processing'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_videos_processing_started_at', table_name='videos', postgresql_where=sa.text("status = 'processing'"))
    op.drop_column('videos', 'failure_reason')
    op.drop_column('videos', 'processing_started_at')
    # ### end Alembic commands ###
